# Ref. https://www.youtube.com/watch?v=BAXvzkgL15o
# https://damienaicheh.github.io/flutter/github/actions/2021/04/22/build-sign-flutter-ios-github-actions-en.html
# https://github.com/damienaicheh/demo_flutter_github_actions/tree/main/.github/workflows
#  To get UUID - provisioning certificate
#  security find-identity -v -p codesigning

name: CI
on:
  push:
    branches:
      - master
      - develop
jobs:
  build_ipa:
    name: Build Flutter (iOS)
#    runs-on: macos-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Check and Delete Existing Keychain
        run: |
          keychain_name="signing_temp.keychain"
          if security list-keychains | grep -q $keychain_name; then
            echo "Deleting existing keychain: $keychain_name"
            security delete-keychain $keychain_name
          fi
      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.P12_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}
      - name: Install the provisioning profile
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build ios --flavor prod -t lib/main_prod.dart --no-codesign
      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme prod -configuration Release-Prod
      - name: Build xArchive
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme prod -configuration Release-Prod DEVELOPMENT_TEAM=DVZ87WX9KT -sdk 'iphoneos' -destination 'generic/platform=iOS' -archivePath build-output/app.xcarchive PROVISIONING_PROFILE=7DD26ACBB6D1F373E03240ECC41A4C5683B919D8 clean archive CODE_SIGN_IDENTITY="iPhone Distribution" IPHONEOS_DEPLOYMENT_TARGET=11.0
      - name: Export ipa
        run: xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist
      - name: Publish iOS Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-ipa
          path: build-output/ios

#  build_apk:
#    name: Build Flutter (Android)
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: "12.x"
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: "stable"
#      - run: flutter clean
#      - run: flutter pub get
#      - run: flutter build apk --flavor prod -t lib/main_prod.dart
#      - name: Upload apk as Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: flutter-apk
#          path: build/app/outputs/flutter-apk

#  build_ios_without_sign_in:
#    name: Build Flutter (iOS)
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: "stable"
#      - run: flutter clean
#      - run: flutter pub get
#      - run: |
#          cd ios
#          if [ -f "Podfile.lock" ]; then
#            rm Podfile.lock
#          fi
#          pod deintegrate
#          pod repo update
#          pod install
#      - run: |
#          flutter build ios --flavor prod -t lib/main_prod.dart --no-codesign
#          cd build/ios/iphoneos
#          mkdir Payload
#          cd Payload
#          ln -s ../Runner.app
#          cd ..
#          zip -r app.ipa Payload
#      - name: Upload ipa as Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: flutter-ipa
#          path: build/ios/iphoneos/app.ipa